check for sed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,6 +9,8 @@ fi
 echo "Checking for essential build tools..."
 command -v cc >/dev/null 2>&1 || { echo >&2 "GCC is required but not installed. Aborting."; exit 1; }
 command -v make >/dev/null 2>&1 || { echo >&2 "Make is required but not installed. Aborting."; exit 1; }
+command -v sed >/dev/null 2>&1 }|| { echo >&2 "sed is required but not installed. Aborting."; exit 1; }
+
 
 # If minimal build, exit here
 if [ "$MINIMAL_BUILD" = true ]; then
